<?php

$disabled = '';
$disabled = ! get_permissoes($_SESSION[USERDATA], 'banners', 'remover') ? $disabled = 'disabled="disabled"' : '';

$option['recordsTotal'] = $recordsTotal;
$option['recordsFiltered'] = $recordsFiltered;
$option['data'] = array();

$status = array(
	'0' => 'INATIVO',
	'1' => 'ATIVO',
	'A' => 'Agendada'
);
$color = array(
	'0' => 'danger',
	'1' => 'success',
	'A' => 'warning'
);
$icon = array(
	'0' => 'folder-o',
	'1' => 'check',
	'A' => 'clock-o'
);
$muted = array(
	'0' => 'muted',
	'1' => '1',
	'A' => 'text-warning'
);

if ( $query -> numRows() > 0 )
{

	$banner = new \App\Entities\Banner;

	foreach ( $query -> result() as $row )
	{

		$row = $banner -> fill($row);
		
		$rows = array();

		$rows[] = '<div class="center-align " data-clickable="false">
    					<label>
    						<input type="checkbox" name="banners[]" class="trash" value="' . $row -> getId() . '" ' . $disabled . '>
    						<span></span>
    					<label>
					</div>';

		$rows[] = '<div class="center-align sts ' . $muted[$row -> getStatus()] . '"> ' . $row -> getId() . ' </div>';

		$rows[] = '	<div class="center-align ' . $muted[$row -> getStatus()] . '" data-clickable="false">
						<img class="materialbox" src="' . $row -> getImagem(true) . '" alt="' . ( ! empty($row -> getDescricao()) ? substr($row -> getDescricao(), 0, 200) : '') . '" width="60" height="30">
					</div>';

		$rows[] = '<div class="' . $muted[$row -> getStatus()] . '"> ' . ( $row -> getTitulo() ?? '-') . ' </div>';
		// $rows[] = '<div class="' . $muted[$row -> getStatus()] . '">' . ( $row -> getCidade() ?? 'Não atribuído') . '</div>';
		// $rows[] = '<div class="' . $muted[$row -> getStatus()] . '">' . ( $row -> getBairro() ?? 'Não atribuído')  . '</div>';
		$rows[] = '<div class="' . $muted[$row -> getStatus()] . '">' . ( $row -> getAutor() ?? 'Não atribuído')  . '</div>';

		$rows[] = '<div class="center-align ' . $muted[$row -> getStatus()] . '"> ' . ($row -> getDataAdd('d/m/Y H:i:s') ?? '-') . ' </div>';

		$status = '<i class="material-icons teal-text" data-tooltip="Ativo"> sentiment_satisfied </i>';

		if ( isset($row) && $row -> getStatus() === '0' )
			$status = '<i class="material-icons red-text" data-tooltip="Inativo"> sentiment_very_dissatisfied </i>';

		$rows[] = '	<div class="switch center-align"> ' . $status . ' </div>';

		$rows[] = '	<div class="center-align">
						<button type="button" class="btn blue waves-effect waves-light" data-tooltip="Editar #' . $row -> getId() . '" onclick="modal_edit();">
							<i class="material-icons">edit</i>
						</button>
					</div>';

		$option['data'][] = $rows;

	}

}

echo json_encode($option);
