<!-- styles | fonts  -->
<link type="text/css" rel="stylesheet" media="screen" href="<?= base_path(); ?>fonts/material-design-icons/material-icons.css">
<link type="text/css" rel="stylesheet" media="screen" href="<?= base_path(); ?>fonts/muli/muli.css">
<link type="text/css" rel="stylesheet" media="screen" href="<?= base_path(); ?>fonts/icons/icons.css">

<!-- styles | vendors -->
<link type="text/css" rel="stylesheet" media="screen" href="<?= base_path(); ?>plugins/vendors/css/materialize.css">
<link type="text/css" rel="stylesheet" media="screen" href="<?= base_path(); ?>plugins/vendors/css/animate.min.css">
<link type="text/css" rel="stylesheet" media="screen" href="<?= base_path(); ?>plugins/vendors/css/flag-icon.min.css">
<link type="text/css" rel="stylesheet" media="screen" href="<?= base_path(); ?>plugins/vendors/css/perfect-scrollbar.css">

<!-- styles | chartist -->
<link type="text/css" rel="stylesheet" media="screen" href="<?= base_path(); ?>plugins/chartist/chartist.min.css">
<link type="text/css" rel="stylesheet" media="screen" href="<?= base_path(); ?>plugins/chartist/chartist-plugin-tooltip.css">

<!-- styles | datatables -->
<link type="text/css" rel="stylesheet" media="screen" href="<?= base_path(); ?>plugins/datatable/css/jquery.dataTables.min.css">
<link type="text/css" rel="stylesheet" media="screen" href="<?= base_path(); ?>plugins/datatable/css/datatables.responsive.min.css">

<!-- plugins | select2 -->
<link type="text/css" rel="stylesheet" media="screen" href="<?= base_path(); ?>plugins/select2/select2.css">
<link type="text/css" rel="stylesheet" media="screen" href="<?= base_path(); ?>plugins/select2/select2-materialize.css">

<!-- plugins | nouislider -->
<link type="text/css" rel="stylesheet" media="screen" href="<?= base_path(); ?>plugins/nouislider/nouislider.css">

<!-- plugins | magnific-popup -->
<link type="text/css" rel="stylesheet" media="screen" href="<?= base_path(); ?>plugins/magnific-popup/magnific-popup.css">

<!-- styles | quill - editor de texto -->
<link type="text/css" rel="stylesheet" media="screen" href="<?= base_path(); ?>plugins/materialnote/materialnote.css">
<link type="text/css" rel="stylesheet" media="screen" href="<?= base_path(); ?>plugins/sweetalert/sweetalert.css">

<!-- styles | defaults.css -->
<link type="text/css" rel="stylesheet" media="screen" href="<?= base_path(); ?>css/style.css">
<link type="text/css" rel="stylesheet" media="screen" href="<?= base_path(); ?>css/loader.css">
<link type="text/css" rel="stylesheet" media="screen" href="<?= base_path(); ?>css/datatable.css">

<?php if ( ! isset($_SESSION[USERDATA]) ) : ?>
<link type="text/css" rel="stylesheet" media="screen" href="<?= base_path(); ?>css/login.css">
<?php endif; ?>

<!-- styles | outros estilos -->