<?php $disabled = null; ?>

<form action="<?php echo base_url(); ?>planos" method="post" enctype="multipart/form-data" id="frm-plano" autocomplete="off">

    <!-- modal-content -->
    <div class="modal-content no-padding">

    	<!-- modal-header -->
    	<div class="modal-header">

			<ul class="tabs tabs-fixed-width z-depth-1" style="background: transparent;">
				<li class="tab">
					<a href="#tab_plano" class="active">
						Plano
					</a>
				</li>
				<!--<li class="tab">-->
				<!--	<a href="#tab_valores">-->
				<!--		Valores-->
				<!--	</a>-->
				<!--</li>-->
				<li class="tab">
					<a href="#tab_cidade">
						Cidades
					</a>
				</li>
			</ul>

    	</div>
    	<!--/modal-header -->

    	<!-- modal-body -->
    	<div class="modal-body no-padding">

    		<!-- row -->
    		<div class="row">

    			<!-- col -->
    			<div class="col s12 m6 offset-s0 offset-m3">

    				<!-- #tab_plano -->
    				<div id="tab_plano">

    					<!-- titulo -->
						<div class="input-field-container">
						    <div class="input-field transparent">
    							<label for="titulo" class="<?= isset($row) ? 'active' : null; ?>">
    								Plano
    							</label>
    							<input type="text" name="titulo" value="<?= isset($row) ? $row -> getTitulo() : null; ?>" id="titulo">
    							<div class="line-ripple indigo"></div>
    						</div>
    						<div class="helper-line">
							    <div class="helper-text"></div>
							    <div class="helper-counter"></div>
							</div>
    					</div>
    					<!--/titulo -->

    					<!-- tipo -->
    					<div class="input-field-container">
    						<div class="input-field transparent">
								<?php
								$option = null;
								if ( isset($tipos) )
								{
									foreach ($tipos as $tipo ) {
										$option .= '<option class="indigo-text" value="' . $tipo -> id . '"
											' . ( isset($row) && $row -> getIdTipo() == $tipo -> id ? 'selected="selected"' : NULL ). '>' . $tipo -> tipo . '</option>';
									}
								}
								?>
    							<select name="tipo">
    								<option value="" selected="selected" disabled="disabled">Tipo do plano</option>
    								<?= $option; ?>
    							</select>
    							<label for="tipo" class="<?= isset($row) ? '' : null; ?>">
    								Tipo de plano
    							</label>
    						</div>
    						<div class="helper-line">
							    <div class="helper-text"></div>
							    <div class="helper-counter"></div>
							</div>
    					</div>
    					<!--/tipo -->

    					<!-- plano -->
						<div class="input-field-container">
						    <div class="input-field transparent">
    							<label for="descricao" class="<?= isset($row) ? 'active' : null; ?>">
    								Descrição
    							</label>
    							<input type="text" name="descricao" value="<?= isset($row) ? $row -> getDescricao() : null; ?>" id="descricao">
    							<div class="line-ripple indigo"></div>
    						</div>
    						<div class="helper-line">
							    <div class="helper-text"></div>
							    <div class="helper-counter"></div>
							</div>
    					</div>
    					<!--/plano -->

    					<!-- velocidade_upload -->
						<div class="input-field-container">
						    <div class="input-field transparent">
    							<i class="material-icons prefix indigo-text">cloud_upload</i>
    							<label for="velocidade_upload" class="<?= isset($row) ? 'active' : null; ?>">
    								Velocidade de upload
    							</label>
    							<input type="number" name="velocidade_upload" value="<?= isset($row) ? $row -> getVelocidadeUpload() : null; ?>" id="velocidade_upload">
    							<div class="line-ripple indigo"></div>
    						</div>
    						<div class="helper-line">
							    <div class="helper-text"></div>
							    <div class="helper-counter"></div>
							</div>
    					</div>
    					<!--/velocidade_upload -->

    					<!-- velocidade_download -->
						<div class="input-field-container">
						    <div class="input-field transparent">
    							<i class="material-icons prefix indigo-text">cloud_download</i>
    							<label for="velocidade_download" class="<?= isset($row) ? 'active' : null; ?>">
    								Velocidade de download
    							</label>
    							<input type="number" name="velocidade_download" class="is_number" value="<?= isset($row) ? $row -> getVelocidadeDownload() : null; ?>" id="velocidade_download">
    							<div class="line-ripple indigo"></div>
    						</div>
    						<div class="helper-line">
							    <div class="helper-text"></div>
							    <div class="helper-counter"></div>
							</div>
    					</div>
    					<!--/velocidade_download -->

                    	<!-- valor_mensal -->
						<div class="input-field-container">
						    <div class="input-field transparent">
    							<i class="material-icons prefix indigo-text">attach_money</i>
    							<label for="valor_mensal" class="active">
    								Valor Mensal (R$)
    							</label>
    							<input type="text" name="valor_mensal" maxlength="6" class="is_decimal" data-value="<?= isset($row) ? $row -> getValorMensal() : null; ?>" id="taxa_instalacao">
    							<div class="line-ripple indigo"></div>
    						</div>
    						<div class="helper-line">
							    <div class="helper-text"></div>
							    <div class="helper-counter"></div>
							</div>
    					</div>
    					<!--/valor_mensal -->

    					<!-- nível --
						<div class="input-field-container">
    						<p class="range-field">
    							<label for="nivel" class="<?= isset($row) ? 'active' : null; ?>">
    								Classificação
    							</label>
    							<div id="nivel"></div>
    							<input type="hidden" name="nivel">
    						</p>
    						<div class="helper-line">
							    <div class="helper-text"></div>
							    <div class="helper-counter"></div>
							</div>
    					</div>
    					<!--/nível -->

    					<!-- wifi incluso -->
						<div class="input-field-container">
						    <div class="input-field transparent">
    							<?php
    							$checked = null;
    							if ( isset($row) && $row -> getWifiIncluso() === 'S' )
    								$checked = 'checked="checked"';
    							?>
    							<div for="wifi_incluso" class="switch font-weight-600 left">
    								<label for="wifi_incluso" class="left">
    									Wifi Incluso
    								</label>
    								<label class="indigo right">
										<input type="checkbox"
											   name="wifi_incluso"
											   class="right"
											   id="wifi_incluso"
											   value="1"
											   <?= $checked; ?>>
    									<span class="lever right"></span>
    								</label>
    							</div>
    						</div>
    						<div class="helper-line">
							    <div class="helper-text"></div>
							    <div class="helper-counter"></div>
							</div>
    					</div>
    					<!--/wifi_incluso -->

    					<!-- status -->
						<div class="input-field-container">
						    <div class="input-field transparent">
    							<?php
    							$checked = 'checked="checked"';
    							if ( isset($row) && $row -> getStatus() === '0' )
    								$checked = null;
    							?>
    							<div class="switch font-weight-600 left">
    								<label for="status" class="left">
    									Exibir
    								</label>
    								<label class="indigo right">
										<input type="checkbox"
											   name="status"
											   class="right"
											   id="status"
											   value="1"
											   <?= $checked; ?>>
    									<span class="lever right"></span>
    								</label>
    							</div>
    						</div>
    						<div class="helper-line">
							    <div class="helper-text"></div>
							    <div class="helper-counter"></div>
							</div>
    					</div>
    					<!--/status -->

    				</div>
    				<!--/#tab_plano -->

    				<!-- #tab_valores -->
    				<!--<div id="tab_valores">-->

                        <!-- taxa_instalacao -->
						<!--<div class="input-field-container">-->
						<!--    <div class="input-field transparent">-->
    		<!--					<i class="material-icons prefix indigo-text">attach_money</i>-->
    		<!--					<label for="taxa_instalacao" class="active">-->
    		<!--						Taxa de Instalação (R$)-->
    		<!--					</label>-->
    		<!--					<input type="text" name="taxa_instalacao" maxlength="6" class="is_decimal" data-value="<?= isset($row) ? $row -> getTaxaInstalacao() : null; ?>" id="taxa_instalacao">-->
    		<!--					<div class="line-ripple indigo"></div>-->
    		<!--				</div>-->
    		<!--				<div class="helper-line">-->
						<!--	    <div class="helper-text"></div>-->
						<!--	    <div class="helper-counter"></div>-->
						<!--	</div>-->
    		<!--			</div>-->
    					<!--/taxa_instalacao -->

    					<!-- taxa_cancelamento -->
						<!--<div class="input-field-container">-->
						<!--    <div class="input-field transparent">-->
    		<!--					<i class="material-icons prefix indigo-text">attach_money</i>-->
    		<!--					<label for="taxa_cancelamento" class="active">-->
    		<!--						Taxa de Cancelamento (R$)-->
    		<!--					</label>-->
    		<!--					<input type="text" name="taxa_cancelamento" maxlength="6" class="is_decimal" data-value="<?= isset($row) ? $row -> getTaxaCancelamento() : null; ?>" id="taxa_cancelamento">-->
    		<!--					<div class="line-ripple indigo"></div>-->
    		<!--				</div>-->
    		<!--				<div class="helper-line">-->
						<!--	    <div class="helper-text"></div>-->
						<!--	    <div class="helper-counter"></div>-->
						<!--	</div>-->
    		<!--			</div>-->
    					<!--/taxa_cancelamento -->
    				<!--</div>-->
    				<!--/#tab_valores -->

    				<!-- #tab_cidade -->
    				<div id="tab_cidade">
    					<!-- input-field -->
					    <div class="input-field-container">
					        <div class="input-field transparent">
    					    	<label>
    						    	Atribuir Cidades ou Bairros:
    							</label>
								<br><br>
								<?php
								// $planos_bairros = new \App\Models\PlanoModel();
								if ( isset($cidades) )
								{

									$c = null;
									$checked = null;
									$selected = null;
									$disabled = null;

									foreach ( $cidades as $cidade )
									{
										$c        = isset($row) ? $planos -> getPlanoBairro(['id_plano' => $row -> getId(), 'P.id_cidade' => $cidade -> id]) -> limit(1) -> getRow() : null;
										$checked  = isset($row) && ! is_null($c) && $c -> id_cidade == $cidade -> id ? 'checked="checked"' : null;
										$selected = isset($row) && ! is_null($c) && $c -> id_cidade == $cidade -> id ? 'selected' : null;
								?>
								<table id="cidade_<?= $cidade -> id; ?>" class="table striped highlight bulk_action window--table bordered">
									<thead>
										<tr class="<?= $selected; ?>">
											<th class="<?= $selected; ?> mini-cell" colspan="2">
												<label>
													<input type="checkbox" <?= $checked; ?> id="selectAllBairros_<?= $cidade -> id; ?>">
													<span>Cidade: <?= $cidade -> cidade; ?></span>
												</label>
											</th>
											
										</tr>
									</thead>
									<tbody>
										<?php

										$all_bairros = $bairros -> getBairroUsuario(['B.id_cidade' => $cidade -> id]) -> getAll();
										if ( isset($all_bairros) )
										{
											foreach ( $all_bairros as $bairro )
											{
												$b        = isset($row) ? $planos -> getPlanoBairro(['P.id_plano' => $row -> getId(), 'P.id_bairro' => $bairro -> id]) -> limit(1) -> getRow() : null;
												$checked  = isset($row) && ! is_null($b) && $b -> id_bairro == $bairro -> id ? 'checked="checked"' : null;
												$selected = isset($row) && ! is_null($b) && $b -> id_bairro == $bairro -> id ? 'selected' : null;
										?>
											<tr>
												<td class="<?= $selected; ?> small-cell" style="overflow: hidden; position: relative;">
												    <label for="<?= $bairro -> id; ?>" class="waves-effect" style="position: absolute;width: 100%;height: 100%;top: 0px;left: 0;"></label>
													<div class="">
														<label>
															<input type="checkbox" 	name="bairros[]" value="<?= $cidade -> id . ':' . $bairro -> id; ?>" <?= $checked; ?> id="<?= $bairro -> id; ?>">
															<span><?= $bairro -> bairro; ?></span>
														</label>
													</div>
												</td>
											</tr>
										<?php
											}
										}
										?>
									</tbody>
								</table>
								<?php
									}
								}
								?>
    					    </div>
    					    <div class="helper-line">
							    <div class="helper-text"></div>
							    <div class="helper-counter"></div>
							</div>
    					</div>
    					<!--/input-field -->
    				</div>
    				<!--/#tab_cidade -->

    			</div>
    			<!--/col -->
    		</div>
    		<!--/row -->

    	</div>
    	<!--/modal-body -->

    	<!-- .modal-footer -->
    	<div class="modal-footer hide">

    		<button type="reset" class="modal-close waves-effect btn-flat left" data-tooltip="Cancelar" data-position="right">
    			<i class="material-icons left hide-on-small-only">close</i>
    			<span>
    				Cancelar
    			</span>
    		</button>

    		<button type="submit" name="salvar" value="salvar" class="btn btn-primary teal waves-effect waves-light btn-small" data-tooltip="Salvar" data-position="left">
    			<i class="material-icons left hide-on-small-only">save</i>
    			<span>
    				Salvar
    			</span>
    		</button>

    		<input type="hidden" name="id" value="<?= isset($row) ? $row -> getId() : null; ?>">
    		<input type="hidden" name="action" class="action" value="salvar">
    		<input type="hidden" name="_method" value="<?= $method; ?>">

    	</div>
    	<!--/.modal-footer  -->

	</div>
	<!--/modal-content -->

</form>

<script>
	load_plugins();
	load_functions();

	$(document).ready(function()
	{
		$('.tabs').tabs();

		Apps.checkAll();
	});

</script>
