<!-- # begin content -->
<div id="content" class="row">

	<!-- # begin main -->
	<div id="main">

		<div class="row">
			<div class="tela">
				<img src="/assets/pjmtelecom/img/tela.jpg" class="img_cem">
			</div>
		</div>

		<div class="row">
			<div class="tela_mob">
				<img src="/assets/pjmtelecom/img/tela_mob.jpg" class="img_cem">
			</div>
		</div>

		<div class="row">

			<div class="col s12 m7 l4 offset-l2" style="margin-top: 20%">

				<div class="card blue-dark darken-1 white bg-opacity-6">

					<div class="card-content">

						<?= configuracoes('msg_bloqueio_temporario'); ?>
					</div>

				</div>

			</div>

		</div>

	</div>
	<!-- end main -->

</div>
<!-- end content -->
