<form action="<?php echo base_url(); ?>comunicados" method="post" enctype="multipart/form-data" id="frm-delete-comunicado" autocomplete="off">
    <div class="breadcrumbs-dark" id="breadcrumbs-wrapper">
    	<div class="container">
    		<div class="row">
    			<div class="col s10 m6 l6">
    				<h5 class="breadcrumbs-title mt-0 mb-0">
    					Comunicados
    				</h5>
    				<ol class="breadcrumbs mb-0">
    					<li class="breadcrumb-item">
    						<a href="<?= base_url(); ?>dashboard">
    							Dashboard
    						</a>
    					</li>
    					<li class="breadcrumb-item active">
    						Comunicados
    					</li>
    				</ol>
    			</div>
    			<div class="col s2 m6 l6">
    					<div class="bulk-actions right">
    						<div class="hide-on-med-and-down">
    
    							<button type="button"
	    							class="btn blue waves-effect waves-light pink modal-trigger"
	    							data-href="<?= base_url(); ?>comunicados/add"
	    							data-toggle="modal"
	    							data-target="modal-comunicado"
	    							data-tooltip="Adicionar Comunicado"
	    							data-type="html">
    								<i class="material-icons left">add</i>
    								Adicionar
    							</button>
    
    							<button type="submit" name="excluir"
	    							class="btn btn-danger red btn-excluir"
	    							disabled="disabled"
	    							data-tooltip="Excluir Comunicado">
    								<i class="material-icons left">delete</i>
    								Excluir
    							</button>
    
    						</div>
    
    						<div class="btn-group hide-on-large-only">
    
    							<div class="fixed-action-btn direction-top">
    
    								<button type="button" class="btn-floating btn-large btn-inserir blue waves-effect waves-light modal-trigger animated" data-toggle="modal"
    								data-target="modal-comunicado" data-tooltip="Adicionar Comunicado" data-position="left" data-href="<?= base_url(); ?>comunicados/add" data-type="html">
    									<i class="material-icons">add</i>
    								</button>
    
    								<button type="submit" name="excluir"
    								class="btn-floating btn-large btn-danger red btn-excluir animated hide"
    								disabled="disabled"
    								data-tooltip="Excluir Enquete">
    									<i class="material-icons left">delete</i>
    								</button>
    
    							</div>
    
    						</div>
    					</div>
    				</div>
    		</div>
    	</div>
    </div>
    
    	<div class="container">
    		<div class="row">
    			<div class="col s12">
    				<table class="table datatable bulk_action striped"
    					id="comunicado"
    					data-toggle="modal"
    					data-placeholder="Pesquisar Comunicados"
    					data-title="Editar Comunicado"
    					data-type="html">
    					<thead>
    						<tr>
    							<th class="center-align mini-cell" data-clickable="false">
    								<label>
    									<input type="checkbox" id="check-all" class="trash" value="">
    									<span>
    									</span>
    								</label>
    							</th>
    							<th class="center-align mini-cell">
    								#
    							</th>
    							<th class="big-cell">
    								Título
    							</th>
    							<th class="left-align medium-cell">
    								Descrição
    								<i class="material-icons left hide-on-small-only">cloud_download</i>
    							</th>
    							<th class="left-align medium-cell">
    								Agendamento
    								<i class="material-icons left hide-on-small-only">cloud_upload</i>
    							</th>
    							<th class="left-align medium-cell">
    								Data de Criação
    								<i class="material-icons left hide-on-small-only">wifi</i>
    							</th>
    							<th class="left-align mini-cell">
    								Situação
    							</th>
    							<th class="center-align mini-cell" data-clickable="false">
    								<i class="material-icons">edit</i>
    							</th>
    						</tr>
    					</thead>
    				</table>
    			</div>
    		</div>
    	</div>
    	<input type="hidden" name="_method" value="delete">
</form>

<!-- modal-comunicado -->
<div id="modal-comunicado" class="modal full-screen modal-fixed-header" data-dismissible="false">

</div>
<!--/modal-comunicado -->

