<div class="container mt-10" style="min-height: 800px;">

	<div class="row">

		<div class="col s12 m9">

			<h3>
				Quem Somos
			</h3>

			<div class="txt_page" style="line-height: 2rem">
				<?php echo configuracoes('texto_apresentacao'); ?>
			</div>

		</div>

		<div class="col s12 m3">

			<div class="col_right">
				<?php
				include VIEWPATH . '' . DS . 'right.php';
				?>
			</div>

		</div>

	</div>

</div>
