<?php

$disabled = '';
$disabled = ! get_permissoes($_SESSION[USERDATA], 'usuarios', 'remover') ? $disabled = 'disabled="disabled"' : '';

$option['recordsTotal'] = $recordsTotal;
$option['recordsFiltered'] = $recordsFiltered;
$option['data'] = array();

$status = array(
	'0' => 'INATIVO',
	'1' => 'ATIVO',
	'A' => 'Agendada'
);
$color = array(
	'0' => 'danger',
	'1' => 'success',
	'A' => 'warning'
);
$icon = array(
	'0' => 'folder-o',
	'1' => 'check',
	'A' => 'clock-o'
);
$muted = array(
	'0' => 'muted',
	'1' => '1',
	'A' => 'text-warning'
);

if ( $query -> numRows() > 0 )
{

	$usuario = new \App\Entities\User;

	foreach ( $query -> result() as $row )
	{

		$row = $usuario -> fill($row);
		
		$rows = array();

		$rows[] = '<div class="center-align " data-clickable="false">
					<label>
						<input type="checkbox" name="usuarios[]" class="trash" value="' . $row -> getId() . '" ' . $disabled . '>
						<span></span>
					<label>
					</div>';

		$rows[] = '<div class="center-align sts ' . $muted[$row -> getStatus()] . '"> ' . $row -> getId() . ' </div>';

		$rows[] = '<div class="sts ' . $muted[$row -> getStatus()] . '"> ' . $row -> getNome() . ' </div>';

		$rows[] = '<div class="left-align ' . $muted[$row -> getStatus()] . '">
				   		 ' . $row -> getNomeGrupo($row -> getIdGrupo()) . '
				   </div>';
				   
		$rows[] = ' <div class="left-align ' . $muted[$row -> getStatus()] . '">
						' . ( $row -> getNomeGestor($row -> getIdGestor()) ?? '-' ). '
					</div>';

		$rows[] = '<div class="left-align ' . $muted[$row -> getStatus()] . '">
				   		 ' . $row -> getEmail() . '
				   </div>';

		$rows[] = '<div class="center-align ' . $muted[$row -> getStatus()] . '">
						' . ( $row -> getUltimoLogin('d/m/Y H:i:s') ?? '-' ). '
				   </div>';

		$status = '<i class="material-icons teal-text" data-tooltip="Ativo"> sentiment_satisfied </i>';
		if ( isset($row) && $row -> getStatus() === '0' )
			$status = '<i class="material-icons red-text" data-tooltip="Inativo"> sentiment_very_dissatisfied </i>';

		$rows[] = '	<div class="switch center-align ' . $muted[$row -> getStatus()] . '">
						' . $status . '
					</div>';

		$rows[] = '	<div class="center-align">
						<button type="button" class="btn blue waves-effect waves-light" data-tooltip="Editar #' . $row -> getId() . '" onclick="modal_edit();">
							<i class="material-icons">edit</i>
						</button>
					</div>';

		$option['data'][] = $rows;

	}

}

echo json_encode($option);
