<form action="<?php echo base_url(); ?>usuarios" method="post" enctype="multipart/form-data" id="frm-delete-usuario" autocomplete="off">

	<div class="breadcrumbs-dark" id="breadcrumbs-wrapper">
		<div class="container">
			<div class="row">
				<div class="col s10 m6 l6">
					<h5 class="breadcrumbs-title mt-0 mb-0">
						Usuários
					</h5>
					<ol class="breadcrumbs mb-0">
						<li class="breadcrumb-item">
							<a href="<?= base_url(); ?>dashboard">
								Dashboard
							</a>
						</li>
						<li class="breadcrumb-item active">
							Usuários
						</li>
					</ol>
				</div>
				<div class="col s2 m6 l6">
					<div class="bulk-actions right">
						<div class="hide-on-med-and-down">

							<button type="button"
								class="btn blue waves-effect waves-light pink modal-trigger"
								data-href="<?= base_url(); ?>usuarios/add"
								data-toggle="modal"
								data-target="modal-usuario"
								data-tooltip="Adicionar Usuário"
								data-type="html">
								<i class="material-icons left">add</i>
								Adicionar
							</button>

							<button type="submit" name="excluir"
								class="btn btn-danger red btn-excluir"
								disabled="disabled"
								data-tooltip="Excluir Usuário">
								<i class="material-icons left">delete</i>
								Excluir
							</button>

						</div>

						<div class="btn-group hide-on-large-only">

							<div class="fixed-action-btn top right">

								<button type="button" class="btn-floating btn-large btn-inserir blue waves-effect waves-light modal-trigger animated" data-toggle="modal"
									data-target="modal-usuario" data-tooltip="Adicionar Usuário" data-position="left" data-href="<?= base_url(); ?>usuarios/add" data-type="html">
									<i class="material-icons">add</i>
								</button>

								<button type="submit" name="excluir"
									class="btn-floating btn-large btn-danger red btn-excluir animated hide"
									disabled="disabled"
									data-tooltip="Excluir Enquete">
									<i class="material-icons left">delete</i>
								</button>

							</div>

						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="container">

		<div class="row">

			<div class="col s12">

				<table class="table datatable bulk_action striped"
					id="usuario"
					data-toggle="modal"
					data-placeholder="Pesquisar Usuários"
					data-title="Editar Usuário"
					data-type="html">
					<thead>
						<tr>
							<th class="center-align mini-cell" data-clickable="false">
								<label>
									<input type="checkbox" id="check-all" class="trash" value="">
									<span>
									</span>
								</label>
							</th>
							<th class="center-align mini-cell">
								#
							</th>
							<th class="big-cell">
								Nome
							</th>
							<th class="left-align medium-cell">
								Grupo
							</th>
							<th class="left-align medium-cell">
								Gestor
							</th>
							<th class="left-align medium-cell">
								E-mail
							</th>
							<th class="left-align medium-cell">
								Último Login
							</th>
							<th class="left-align mini-cell">
								Situação
							</th>
							<th class="center-align mini-cell" data-clickable="false">
								<i class="material-icons">edit</i>
							</th>
						</tr>
					</thead>
				</table>
			</div>
		</div>
	</div>
	<input type="hidden" name="_method" value="delete">
</form>

<!-- modal-comunicado -->
<div id="modal-usuario" class="modal full-screen modal-fixed-header" data-dismissible="false">

</div>
<!--/modal-comunicado -->

