<?php

$return = array();

$id_bairro_selected = (isset($_COOKIE['cidade']) ? $_COOKIE['cidade'] : null);
$id_cidade_selected = (isset($_COOKIE['bairro']) ? $_COOKIE['bairro'] : null);

if ( $bairros -> numRows() > 0 ) :

	foreach ( $bairros -> result() as $bairro ) :

		$return[] = array(
			'id' => $bairro -> id,
			'text' => $bairro -> bairro
		);

	endforeach;

	$return['cidade_selected'] = $id_cidade_selected;
	$return['bairro_selected'] = $id_bairro_selected;

else :

	$return = array(
		'type' => 'error',
		'msg' => 'nenhum bairro cadastrado para esta cidade.'
	);

endif;

echo json_encode($return);
