<li>
	<a href="<?=base_url(); ?>index" class="waves-effect waves-light">
		INÍCIO
	</a>
</li>
<li>
	<a href="<?=base_url(); ?>quemsomos" class="waves-effect waves-light">
		QUEM SOMOS
	</a>
</li>
<li>
	<a href="<?=base_url(); ?>" class="waves-effect waves-light">
		CENTRAL DO ASSINANTE
	</a>
</li>
<li>
	<a href="<?=base_url(); ?>" class="waves-effect waves-light">
		COBERTURA
	</a>
</li>
<li>
	<a href="<?=base_url(); ?>" class="waves-effect waves-light">
		TESTE DE INTERNET
	</a>
</li>
<li>
	<a href="<?=base_url(); ?>" class="waves-effect waves-light">
		FILMES GRÁTIS
	</a>
</li>